apiVersion : apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: web
          image: pocacr.azurecr.cn/node 
          ports:
          - containerPort: 80